name: ConditionalBaseTrigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description:  "Select the Environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - stage
          - prod
jobs:
   deploy:
      runs-on:  ubuntu-latest

      steps:
        - name: If enviroment is dev
          if: ${{ github.event.inputs.environment == "dev" }}
          run: echo " Deployment is done under Dev
        - name:  If enivorment is stage
          if: ${{ github.event.inputs.environment == "stage" }}
          run: echo " Deployment is under stage"
        - name: if enviorment is stage
          if: ${{ github.event.input.environment == "prod" }}
          run: echo  "Deplpyment done under prod"
