name: Hello-GitAction

on: push

jobs:
     greet:
         runs-on: ubuntu-latest
         steps:
            - name: Say hello to user
              run: echo " Hello Ravi"

            - name: Say good by to evey one
              run: uptime