name: Hello-GitAction

on: push

jobs:
    greet:
         runs-on: ubuntu-latest
         steps:
            - name: Say hello to user
              run: echo " Hello Ravi"

            - name: Say good by to evey one
              run: uptime

            - name: checking current working 
              run: pwd
            - name: Checking current usser created in server
              run: cat /etc/passwd
            - name: multi command steps
              run: |
                echo "Starting the script"
                pwd
                ls -la
                echo "End of script
        
    details:
         runs-on: ubuntu-latest
         steps:
             - name: version of docker and python
               run: docker --version && python --version
