name: Hello-GitAction

on: push

jobs:
    greet:
         runs-on: ubuntu-latest
         steps:
            - name: Say hello to user
              run: echo " Hello Ravi"

            - name: Say good by to evey one
              run: uptime
     details:
         runs-on: ubuntu-latest
         steps:
             - name: version of docker and python
               run: docker --version && python --version